{% set name = "rixs" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c563f92f34db46cd9d01ac1ba3e9c7b41cf206d42dc635bf031ad8ec1cbc0db

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pandas
    - scipy

test:
  imports:
    - rixs
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest --pyargs rixs.tests

about:
  home: https://github.com/scikit-beam/rixs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Analysis tools for resonant inelastic xray scattering.

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
